<!DOCTYPE html>
<html lang="en">

<head>
    
	<meta charset="utf-8">
    <meta name="robots" content="all,follow">
    <meta name="googlebot" content="index,follow,snippet,archive">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="WhyWeWant Organic">
    <meta name="author" content="WhyWeWant Organic">
    <meta name="keywords" content="">

    <title>
        WhyWeWant Organic
    </title>

    <meta name="keywords" content="">
	  <!-- styles -->
	<link href="../font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="../bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="../css/font-awesome.css" rel="stylesheet">
    <!--<link href="../css/bootstrap.css" rel="stylesheet">-->
    <link href="../css/animate.min.css" rel="stylesheet">
    <link href="../css/owl.carousel.css" rel="stylesheet">
    <link href="../css/owl.theme.css" rel="stylesheet">
    <link href="../css/DJ_Theme.css" rel="stylesheet">
    <link href="../css/ihover.min.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- theme stylesheet -->
    <link href="../css/style.default.css" rel="stylesheet" id="theme-stylesheet">

    <!-- your stylesheet with modifications -->
    <link href="../css/custom.css" rel="stylesheet">


    <script src="../js/respond.min.js"></script>

    <!--<link rel="shortcut icon" href="favicon.png">-->
	<link rel="shortcut icon" href="../img/logo4.png">
	
	
    

    
	
    <script src="../js/jquery-1.11.0.min.js"></script>
    <script src="../js/bootstrap.min.js"></script>
</head>
<body>

        <?php include_once("header_topbar.php"); ?>

    	<?php //include_once("header_navbar.php"); ?>
		<hr>





<!-- FAQ - START -->
<div class="container privacy_policy">

    <div class=" row">
          
	    <div class=" col-md-12 col-sm-12">
                
            <div >
				  
				<p class="section-header">
					<h2><span>Terms and Conditions</span></h2>
					
				</p>
				
				<p class="section-header">
					<span >
					
						<span >
						
							<span ><strong><h4>Introduction</h4></strong></span>
							
						
							
							Welcome to the Terms of Use for whywewantorganic.com, a service of WhyWeWant Organic Foods Private Limited. Users of whywewantorganic.com (the "Site") are provided with a wide variety of information and services, including shopping opportunities, access to reviews, and the ability to submit reviews for other users (collectively the "Services"). By using (browsing or shopping on) our Site, you agree to comply with and be bound by the following terms of use (collectively, the "Terms of Use"). Please review the following terms carefully. If you do not agree to any of these terms, please do not use this Site.
							
							<br /> <br /> 
							
							The term "whywewantorganic.com" or "us" or "we" refers to the owner of the Site, WhyWeWant Organic Foods Private Limited. The term "you" refers to the user or viewer of our Site or any of the Services.
							
							<br /> <br /> 
							
							This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
							
							<br/> <br />
							
							<span ><strong><h4>Privacy</h4></strong></span>
							
													
							We view protection of Your privacy as a very important principle. We understand clearly that You and Your Personal Information is one of Our most important assets. We store and process Your Information including any sensitive financial information collected (as defined under the Information Technology Act, 2000), if any, on computers that may be protected by physical as well as reasonable technological security measures and procedures in accordance with Information Technology Act 2000 and Rules there under. Please see our Privacy Policy to understand how we use and share information about you.<br /> <br />
							
							<span ><strong><h4>Changes to the Terms of Use</h4></strong></span>
							
													
							whywewantorganic.com reserves the right to change any of the terms and conditions contained in these Terms of Use or any policies or guidelines governing the Site or Services at any time and in its sole discretion. Changes to the Terms of Use and referenced policies and guidelines may be posted without notice to you.
							
							<br /> <br /> 
							
							When You use any of the services provided by Us through the Website, including but not limited to, (e.g. Product Reviews, Seller Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Website following the posting of changes will mean that You accept and agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.

							<br /> <br /> 

							Accesing, browsing or otherwise using the site indicates your agreemnt to all the terms and conditions under these terms of use, so please read the terms of use carefully before proceeding. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by WhyWeWant Organic Policies ((including but not limited to Privacy Policy available at Privacy) as amended from time to time.Any changes will be effective upon posting of the revisions on the Site. All notice of changes to the Terms of Use will be posted on the Site for thirty (30) days. You are responsible for reviewing the notice and any applicable changes.
							
							<br /> <br /> 
							
										
							 
							
							<span ><strong><h4>Application and Acceptance of the Terms</h4></strong></span>
							
						
							
							Age: Use of the Website is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Website. If you are a minor i.e. under the age of 18 years, you shall not register as a User of the WhyWeWant Organic website and shall not transact on or use the website. As a minor if you wish to use or transact on website, such use or transaction may be made by your legal guardian or parents on the Website. WhyWeWant Organic reserves the right to terminate your membership and / or refuse to provide you with access to the Website if it is brought to WhyWeWant Organic's notice or if it is discovered that you are under the age of 18 years.
							
							<br /> <br /> 
							
							Your Warranties About Use: You warrant to us that you will not purchase any products through the Site which may be harmful based on your allergies (including, without limitation, allergies to peanuts) and/or other medical conditions.&nbsp;You warrant to us that you will properly investigate whether the ingredients of a particular product are suitable for you.&nbsp;
							
						</span>
					</span>
				</p>
				
				<p >
					<span >
						
						<span >whywewantorganic.com reserves the right to list products on the site based on the criteria listed in our website. We screen products based on the ingredient list &amp; certifications products by the manufacturer/vendor.&nbsp;
						
						<br /> <br /> 
						
						Password: Upon registration on the Sites, whywewantorganic.com shall assign an account and issue a member ID and password (the latter shall be chosen by a registered User during registration) to each registered User. An account may have a web-based email account with limited storage space for the Member to send or receive emails.  A set of Member ID and password is unique to a single account. Each Member shall be solely responsible for maintaining the confidentiality and security of your Member ID and password and for all activities that occur under your account. No Member may share, assign, or permit the use of your Member account, ID or password by another person outside of the Member’s own business entity. Member agrees to notify whywewantorganic.com immediately if you become aware of any unauthorized use of your password or your account or any other breach of security of your account
						
						
						
						<br /> <br /> 
						
						You agree to immediately notify whywewantorganic.com of any unauthorized use of your password and/or account identification/username or any breach of security. You also agree that whywewantorganic.com cannot and will not be liable for any loss or damage arising from your failure to keep your password secure.
						
						<br /> <br /> 
						
						Termination of Service: whywewantorganic.com reserves the right to refuse service to anyone for any reason, terminate accounts, remove or edit content, limit, condition or cancel orders in its sole and absolute discretion. Without limiting the foregoing, whywewantorganic.com may, but is not required to, impose transaction limits on some or all Buyers and Sellers relating to the value of any transaction or disbursement, the cumulative value of all transactions or disbursements during a period of time, or the number of transactions per day or other period of time. whywewantorganic.com will not be liable to any Buyer: (i) if whywewantorganic.com does not proceed with a transaction or disbursement that would exceed any limit established by us for a security reason or (ii) if whywewantorganic.com cancels from a transaction.
						
						<br /> <br /> 
						
						
						
						<span ><strong><h4>License &amp; WhyWeWant Organic site Access</h4></strong></span>
						
				
						
						Subject to the terms and conditions of these Terms of Use, whywewantorganic.com hereby grants you a limited, revocable, non-transferable and non-exclusive license to access and use the Site by displaying it on your internet browser only for the purpose of browsing content, shopping for products, uploading reviews, and interacting with other Site users on the Site. Users may not use the Site for any commercial use or use on behalf of any third party, other than sellers explicitly permitted to do so by whywewantorganic.com and who are subject (in addition to these Terms of Use) to the Sellers' Terms and Conditions ("Sellers").
						
						<br /> <br />

						Except as permitted in the paragraph above, you may not reproduce, distribute, display, sell, lease, transmit, create derivative works from, translate, modify, reverse-engineer, disassemble, decompile or otherwise exploit this Site or any portion of it by any means, unless expressly permitted by whywewantorganic.com.
						
						<br /> <br /> 
						
						You may not use the Site or any materials obtained from the Site to develop, or as a component of, any information, storage and retrieval system, database, information base, or similar resource (in any media now existing or hereafter developed), that is offered for commercial distribution of any kind, including through sale, lease, license, rental, subscription, or any other commercial distribution mechanism. You also may not "mirror" or "frame" any material contained on the Site on any other server.
						
						<br /> <br /> 
						
						You many not use any manual or automated software, devices, or other processes to "crawl" or "spider" any web pages contained in the Site. You may not monitor or copy, or allow others to monitor or copy, our web pages or the content included herein. Furthermore, you agree not to take any action that interferes with the proper working of or places an unreasonable load on our infrastructure, including but not limited to unsolicited communications, attempts to gain unauthorized access, or transmission or activation of computer viruses.
						
						<br /> <br />

						You shall not upload to, distribute, or otherwise publish on our Site any content, information, or other material that (a) violates or infringes the copyrights, patents, trademarks, service marks, trade secrets, or other proprietary rights of any person or organization, unless you are the owner of such rights or have permission from their rightful owner to post the material and to grant whywewantorganic.com all of the license rights granted herein; (b) is libellous, threatening, defamatory, obscene, indecent, pornographic, harassing, hateful, racially or ethnically offensive, or encourages conduct that would be considered a criminal offense, or could give rise to any civil or criminal liability under India or international law; (c) includes any bugs, viruses, worms, trap doors, Trojan horses or other harmful code or properties, (d) advertises or solicits business, or (e) impersonates another person.
						
						<br /> <br /> 
						
						Any breach of these Terms of Use may result in the immediate revocation of the license granted above, without notice to you.
						
						<br /> <br /> 
						
						<span ><strong><h4>Links to Third Party Sites</h4></strong></span>
						
											
						All text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music and artwork (collectively, "Content"), is a third party user generated content and whywewantorganic has no control over such third party user generated content as whywewantorganic is merely an intermediary for the purposes of this Terms of Use.

						Except as expressly provided in these Terms of Use, no part of the Website and no Content may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted or distributed in any way (including "mirroring") to any other computer, server, Website or other medium for publication or distribution or for any commercial enterprise, without whywewantorganic's express prior written consent.

						You may use information on the products and services purposely made available on the Website for downloading, provided that You (1) do not remove any proprietary notice language in all copies of such documents, (2) use such information only for your personal, non-commercial informational purpose and do not copy or post such information on any networked computer or broadcast it in any media, (3) make no modifications to any such information, and (4) do not make any additional representations or warranties relating to such documents.

						You shall be responsible for any notes, messages, emails, billboard postings, photos, drawings, profiles, opinions, ideas, images, videos, audio files or other materials or information posted or transmitted to the Website (collectively, "Content"). Such Content will become Our property and You grant Us the worldwide, perpetual and transferable rights in such Content. We shall be entitled to, consistent with Our Privacy Policy as adopted in accordance with applicable law, use the Content or any of its elements for any type of use forever, including but not limited to promotional and advertising purposes and in any media whether now known or hereafter devised, including the creation of derivative works that may include the Content You provide. You agree that any Content You post may be used by us, consistent with Our Privacy Policy and Rules of Conduct on Site as mentioned herein, and You are not entitled to any payment or other compensation for such use.
						<br /> <br /> 
						
						<span ><strong><h4>Intellectual Property</h4></strong></span>
						
					

						whywewantorganic.com is the sole owner or lawful licensee of all the rights and interests in the Sites and the Site Content. The Sites and Site Content embody trade secrets and other intellectual property rights protected under worldwide copyright and other laws. All title, ownership and intellectual property rights in the Sites and Site Content shall remain with whywewantorganic.com, our affiliates or licensors of the Site Content, as the case may be. All rights not otherwise claimed under the Terms or by whywewantorganic.com. 
						
						<br /> <br />

						 "whywewantorganic.com", “WhyWeWant Oragnic Foods” and related icons and logos are registered trademarks or trademarks or service marks of WhyWeWant Organic Foods Limited, and related icons and logos are registered trademarks or trademarks or service marks of whywewantorganic.com, in various jurisdictions and are protected under applicable copyright, trademark and other proprietary rights laws. The unauthorized copying, modification, use or publication of these marks is strictly prohibited.
						
						<br /> <br />

						 whywewantorganic.commay have independent third parties involved in the provision of the Services (e.g., the authentication and verification service providers).  You may not use any trademark, service mark or logo of such independent third parties without prior written approval from such parties.
						
						<br /> <br />

						<span ><strong><h4>Reviews &amp; Comments</h4></strong></span>
						
				

						Users may post reviews on the Site. Anything that you submit or post to the Site and/or provide us (the &ldquo;Submissions&rdquo;), is and will be treated as non-confidential and non-proprietary, and you grant us a royalty-free, worldwide, perpetual, irrevocable and transferable right to use, copy, distribute, display, publish, perform, sell, lease, transmit, adapt, modify, create derivative works from such Submissions by any means and in any form, and to translate, modify, reverse-engineer, disassemble, or decompile such Submissions. You may edit or delete such submissions using the tools provided to you by us on the Site.
						
						<br /> <br /> 
						
						In addition, when you post Submissions to the Site, you also grant us the right to use the name that you submit with any review, comment, or other content, if any, in connection with such review, comment, or other content. You represent and warrant that you own or otherwise control all of the rights to the Submissions that you post on our Site and that use of your reviews, comments, or other Submissions by us will not infringe upon or violate the rights of any third party.
						
						<br /> <br /> You shall not use a false e-mail address, pretend to be someone other than yourself or otherwise mislead us, our affiliates or third parties as to the origin of any Submissions. We have the right, but shall not be obligated to, remove or edit any Submissions for any reason in its sole and absolute discretion.
						
						<br /> <br />

						<span ><strong><h4>Return Policy</h4></strong></span>
						
				
						If a product is listed at an incorrect price or with incorrect information due to typographical error or error in pricing or product information received from a Seller, whywewantorganic.com has the right to refuse or cancel any orders placed for product listed at the incorrect price, whether or not the order has been confirmed and your credit card charged. If the order has been cancelled or refused after a credit card has been charged for the purchase, whywewantorganic.com will issue an immediate and full refund for the transaction amount to the credit card charged.
						
						<br /> <br /> 
						
						<span ><strong><h4>Disclaimer, No Warranty and Limitation of Liability</h4></strong></span>
						
					

						The Site, the Services and the products purchased by you are provided on an &ldquo;as is&rdquo; basis. whywewantorganic.com makes no other representations or warranties of any kind, express, implied or statutory. whywewantorganic.com, and its subsidiaries, affiliates, officers, directors, employees, shareholders, agents, merchants and suppliers specifically disclaim any implied warranties of title, merchantability, performance, fitness for a particular purpose and non-infringement. In addition, no advice or information (oral or written) obtained by you from whywewantorganic.com shall create any warranty. IN ADDITION, TO THE MAXIMUM EXTENT ALLOWABLE BY APPLICABLE LAW, whywewantorganic.com AND ITS SUBSIDIARIES, AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, SHAREHOLDERS AND AGENTS SPECIFICALLY DISCLAIM ALL LIABILITY RESULTING FROM PERSONAL INJURY AND/OR DEATH RESULTING FROM, OR ARISING OUT OF, YOUR USE OR CONSUMPTION OF PRODUCTS OBTAINED FROM SELLERS THROUGH THE SITE OR IN CONNECTION WITH THE SERVICES. Such disclaimer shall include, without limitation, mislabelling of products and/or ingredients. In any such situation, your sole recourse shall be against the Seller who supplied you with the product through our Site. Some states do not allow the disclaimer of implied warranties, so the foregoing disclaimer may not apply to you. This warranty gives you specific legal rights and you may also have other legal rights that vary from state to state.
						
						<br /> <br /> 
						
						Without limiting the foregoing, we do not guarantee continuous, uninterrupted access to the Site or the Services, and operation of the Site may be interfered with by numerous factors outside our control.
						
						<br /> <br />

						<span ><strong><h4>Limitation of Liability</h4></strong></span>
						
					
						
						TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICES PROVIDED BY WHYWEWANTORGANIC.COM ON OR THROUGH THE SITES ARE PROVIDED "AS IS", "AS AVAILABLE" AND “WITH ALL FAULTS”, AND WHYWEWANTORGANIC.COM HEREBY EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, ANY WARRANTIES OF CONDITION, QUALITY, DURABILITY, PERFORMANCE, ACCURACY, RELIABILITY, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. ALL SUCH WARRANTIES, REPRESENTATIONS, CONDITIONS, AND UNDERTAKINGS ARE HEREBY EXCLUDED.
						
						<br /> <br /> 
						
						TO THE MAXIMUM EXTENT PERMITTED BY LAW, WHYWEWANTORGANIC.COM MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE VALIDITY, ACCURACY, CORRECTNESS, RELIABILITY, QUALITY, STABILITY, COMPLETENESS OR CURRENTNESS OF ANY INFORMATION PROVIDED ON OR THROUGH THE SITES; WHYWEWANTORGANIC.COM DOES NOT REPRESENT OR WARRANT THAT THE MANUFACTURE, IMPORTATION, EXPORT, DISTRIBUTION, OFFER, DISPLAY, PURCHASE, SALE AND/OR USE OF PRODUCTS OR SERVICES OFFERED OR DISPLAYED ON THE SITES DOES NOT VIOLATE ANY THIRD PARTY RIGHTS; AND WHYWEWANTORGANIC.COM MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND CONCERNING ANY PRODUCT OR SERVICE OFFERED OR DISPLAYED ON THE SITES.
						
						<br /> <br /> 
						
						Any material downloaded or otherwise obtained through the Sites is done at each User's sole discretion and risk and each User is solely responsible for any damage to whywewantorganic.com’s computer system or loss of data that may result from the download of any such material. No advice or information, whether oral or written, obtained by any User from whywewantorganic.com or through or from the Sites shall create any warranty not expressly stated herein. 
						
						<br /> <br /> 
						
						The Sites may make available to User services or products provided by independent third parties.   No warranty or representation is made with regard to such services or products.   In no event shall whywewantorganic.com and our affiliates be held liable for any such services or products. 
						<br /> <br /> 
						
						Each User hereby agrees to indemnify and save whywewantorganic.com, our affiliates, directors, officers and employees harmless, from any and all losses, claims, liabilities (including legal costs on a full indemnity basis) which may arise from such User's use of the Sites or Services (including but not limited to the display of such User's information on the Sites) or from your breach of any of the terms and conditions of the Terms. Each User hereby further agrees to indemnify and save whywewantorganic.com, our affiliates, directors, officers and employees harmless, from any and all losses, damages, claims, liabilities (including legal costs on a full indemnity basis) which may arise from User's breach of any representations and warranties made by User to whywewantorganic.com, including but not limited. 
						<br /> <br /> 
						
						Each User hereby further agrees to indemnify and save whywewantorganic.com, our affiliates, directors, officers and employees harmless, from any and all losses, damages, claims, liabilities (including legal costs on a full indemnity basis) which may arise, directly or indirectly, as a result of any claims asserted by Third Party Rights claimants or other third parties relating to products offered or displayed on the Sites. Each User hereby further agrees that whywewantorganic.com is not responsible and shall have no liability to you, for any material posted by others, including defamatory, offensive or illicit material and that the risk of damages from such material rests entirely with each User. whywewantorganic.com reserves the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you shall cooperate with whywewantorganic.com in asserting any available defenses. 
						
						<br /> <br /> 
						
						<span ><strong><h4>Indemnity</h4></strong></span>
						
											
						You shall indemnify and hold harmless WhyWeWant Organic, its owner, licensee, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys' fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.
						
						
						<br /> <br /> 
						
						<span ><strong><h4>Termination</h4></strong></span>
						
						
						
						You agree that we may, with or without cause, immediately terminate your account and access to our Site and Services without prior notice. Without limiting the foregoing, the following may lead to the termination by whywewantorganic.com of a user's use of the Site and the Services: (a) breaches or violations of the Terms of Use or other incorporated documents, policies or guidelines, (b) requests by law enforcement or other government agencies, (c) a request by you (self-initiated account deletions), and (d) unexpected technical issues or problems. Termination of your whywewantorganic.com account includes (without liability to whywewantorganic.com): (i) removal of access to all offerings within the Site and the Services, (ii) possible barring you from further use of our Site and Services, and (iii) revoking all password(s) and usernames issued to or chosen by you. Furthermore, you agree that all terminations shall be made in our sole discretion and that we shall not be liable to you nor to any third-party for any termination of your account or access to our Site and Services.
						
						<br /> <br /> 
						
						Any termination of access or of the Terms of Use shall not affect the respective rights and obligations (including without limitation, payment obligations) of the parties arising before the date of termination.
						
						<br /> <br /> 
						
						
						
						<span ><strong><h4>Compliance with Laws</h4></strong></span>
						
				
						
						Buyer and Seller shall comply with all the applicable laws (including without limitation Foreign Exchange Management Act, 1999 and the rules made and notifications issued there under and the Exchange Control Manual as may be issued by Reserve Bank of India from time to time, Customs Act, Information and Technology Act, 2000 as amended by the Information Technology (Amendment) Act 2008, Prevention of Money Laundering Act, 2002 and the rules made there under, Foreign Contribution Regulation Act, 1976 and the rules made there under, Income Tax Act, 1961 and the rules made there under, Export Import Policy of government of India) applicable to them respectively for using Payment Facility and WhyWeWant Organic Website.
						
						<br /> <br /> 
						
						<span ><strong><h4>Copyright Complaints</h4></strong></span>
						
						

						We respect the intellectual property rights of others and we prohibit users from uploading, posting or otherwise transmitting on our Site or in connection with the Services any materials that violate another party's intellectual property rights. When we receive proper Notification of Alleged Copyright Infringement, we promptly remove or disable access to the allegedly infringing material and terminate the accounts of repeat infringers as described herein in accordance with the Digital Millennium Copyright Act.<br /> <br /> If you believe that any content on the Site may give rise to copyright infringement, please provide whywewantorganic.com with the written information specified below.
						
						<br /> <br />

						An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest.
						
						<br /> 
						
						A description of the copyrighted work that you claim has been infringed upon;
						
						<br /> A description of where the material that you claim is infringing is located on the site, including the product name, if applicable;
						<br /> Your address, telephone number, and e-mail address;
						<br /> A statement by you that you have a good-faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law;
						<br /> A statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf.
						<br /> Please send notices to whywewantorganic@gmail.com.
						<br /> Repeat Infringer Policy
						
						<br /> <br /> 
						
						In accordance with the Digital Millennium Copyright Act (DMCA) and other applicable law, Company has adopted a policy of terminating, in appropriate circumstances and at Company's sole discretion, members who are deemed to be repeat infringers. Company may also at its sole discretion limit access to the Site and/or terminate the memberships of any users who infringe any intellectual property rights of others, whether or not there is any repeat infringement.
						
						<br /> <br />

						<span ><strong><h4>Resolution of Disputes and Release</h4></strong></span>
						
					
						
						Generally, transactions are conducted smoothly on WhyWeWant Organic. However there may be some cases where both the Buyers and Sellers may face issues. At WhyWeWant Organic, we have a Dispute Resolution process in order to resolve disputes between Buyers and Sellers.In the event a dispute arises between you and whywewantorganic.com, please contact us at whywewantorganic@gmail.com.
						
						<br /> <br /> A 'Dispute' can be defined as a disagreement between a Buyer and a Seller in connection with a transaction on the Website. Should you have a dispute with one or more users, a Seller, or an outside party, you release whywewantorganic.com (and whywewantorganic.com's officers, directors, agents, subsidiaries, joint ventures and employees) from any and all claims, demands and damages (actual and consequential) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way connected with such disputes.
						
						<br /> <br />

						whywewantorganic.com, for the benefit of users, may try to help users resolve disputes. We do so in our sole discretion, and we have no obligation to resolve disputes between users or between users and outside parties. To the extent that we attempt to resolve a dispute, we will do so in good faith based solely on our policies. We will not make judgments regarding legal issues or claims.
						
						<br /> <br /> 
						
						<span ><strong><h4>Severability</h4></strong></span>
						
				
						
						If any provision of these Terms of Use is held by a court of competent jurisdiction to be unenforceable under applicable law, then such provision shall be excluded from these Terms of Use and the remainder of the Terms of Use shall be interpreted as if such provision were so excluded and shall be enforceable in accordance with its terms; provided, however, that in such event these Terms of Use shall be interpreted so as to give effect, to the greatest extent consistent with and permitted by applicable law, to the meaning and intention of the excluded provision as determined by such court of competent jurisdiction.
						
						<br /> <br /> 
						
						<span ><strong><h4>Notices</h4></strong></span>
						
						  All legal notices or demands to or upon whwewantorganic.com shall be made in writing and sent to whwewantorganic.com personally, by courier, certified mail, or facsimile to the following entity and address: WhyWeWant Orgaic Foods Private Limited, No.18, 3rd Floor, 16th 'C' Main, HAL 2nd Stage, Indiranagar, Bangalore-560008, Karnataka, India. The notices shall be effective when they are received by whwewantorganic.com in any of the above-mentioned manner.
						
						<br /> <br /> 
						
						All legal notices or demands to or upon a User shall be effective if either delivered personally, sent by courier, certified mail, by facsimile or email to the last-known correspondence, fax or email address provided by the User to whwewantorganic.com, or by posting such notice or demand on an area of the Sites that is publicly accessible without a charge. Notice to a User shall be deemed to be received by such User if and when.
						<br /> <br /> 
							
						a) whwewantorganic.com is able to demonstrate that communication, whether in physical or electronic form, has been sent to such User, or
						<br /> <br /> 
						
						b) immediately upon whwewantorganic.com posting such notice on an area of the Sites that is publicly accessible without charge.
						
						<br /> <br /> 
						
						You agree that all agreements, notices, demands, disclosures and other communications that whwewantorganic.com sends to you electronically satisfy the legal requirement that such communication should be in writing. 
						
						<br /> <br /> 
						
						<span ><strong><h4>Contact Information</h4></strong></span>
						
					
						
						If you have any question, you can contact whywewantorganic.com at whywewantorganic@gmail.com or call +91-9900233694</span>
					</span>
				</p>
			</div>
                
        </div>
            
    </div>
        
        
  

</div>
   <?php include_once("footer_links.php");?>
     
	  <?php include_once("final_footer.php");?>

	<!-- *** SCRIPTS TO INCLUDE ***
 _________________________________________________________ -->
   
    <script src="../js/jquery.cookie.js"></script>
    <script src="../js/waypoints.min.js"></script>
    <script src="../js/modernizr.js"></script>
    <script src="../js/bootstrap-hover-dropdown.js"></script>
    <script src="../js/owl.carousel.min.js"></script>
    <script src="../js/front.js"></script>  

</body>
</html>